---
# tasks file for nat-stack-upgrade

- block:
    - git: clone=yes repo=https://github.com/johnpreston/nat-stack-init update=yes force=yes dest=/etc/ansible/roles/nat-stack-init version="{{ init_nat_version }}"
  rescue:
    - git: clone=no repo=https://github.com/johnpreston/nat-stack-init update=yes force=yes dest=/etc/ansible/roles/nat-stack-init version="{{ init_nat_version }}"

- block:
    - git: clone=yes repo=https://github.com/johnpreston/nat-stack-deploy update=yes force=yes dest=/etc/ansible/roles/nat-stack-deploy version="{{ deploy_nat_version }}"
  rescue:
    - git: clone=no repo=https://github.com/johnpreston/nat-stack-deploy update=yes force=yes dest=/etc/ansible/roles/nat-stack-deploy version="{{ deploy_nat_version }}"
